# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "qr-code-app"
client_id = "69fadcd9222514a652665c261a117e25"
application_url = "https://shapes-transaction-conclusion-examples.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_product_listings"

[auth]
redirect_urls = [
  "https://shapes-transaction-conclusion-examples.trycloudflare.com/auth/callback",
  "https://shapes-transaction-conclusion-examples.trycloudflare.com/auth/shopify/callback",
  "https://shapes-transaction-conclusion-examples.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-0af585fe.myshopify.com"
